### ISSUE TITLE
EternalStorage.getStringValue not working

### ISSUE THREAD

**Issue by nrchandan** [elenadimitrova/ContractFactory#1]
Hi Elena, I'm trying to use the concepts in your [blog post](https://blog.colony.io/writing-upgradeable-contracts-in-solidity-6743f0eecc88) to make my own contract upgradable. However, I'm facing problem with returning string types. Apparently, EVM cannot read variably-sized data from external function calls. Pasting the exact error message below for your reference. 

Have you tackled this problem in some way?

`Error: Return argument type inaccessible dynamic type is not implicitly convertible to expected type (type of first return variable) string memory.`

**Comment by elenadimitrova** [comment]
Hi @nrchandan, indeed we cannot read strings within the solidity contracts but you can from the client side via the JS API which is what we can do via `await storage.getStringValue.call([storageKey]);`

**Comment by nrchandan** [comment]
Thank you for the response. Great work with the upgradable contracts! I am adopting your approach in my project too.
- Chandan
